security:
    encoders:
        App\Security\SecurityUser:
            algorithm: bcrypt
        App\Security\User:
            algorithm: bcrypt
    providers:
        db_provider:
            id: App\Security\SecurityUserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: ~

            access_denied_handler: App\Security\AccessDeniedHandler

            logout:
                path: app_logout
                success_handler: App\Security\LogoutSuccessHandler
                invalidate_session: true

            form_login:
                check_path: app_login
                login_path: app_login

            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
                provider: db_provider

    access_control:
      - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }

      - { path: ^/post/(<\d+>)/comment, roles: [ROLE_ADMIN, ROLE_USER] }
      - { path: ^/post/(<\d+>)/comment/edit/(<\d+>), roles: [ROLE_ADMIN, ROLE_USER] }
      - { path: ^/survey/vote, roles: [ROLE_ADMIN, ROLE_USER] }

