security:
    encoders:
        App\Entity\Person:
            algorithm: bcrypt
    providers:
        app_provider:
            entity:
                class: App\Entity\Person
                property: username
        in_memory: { memory: ~ }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true

            access_denied_handler: App\Security\AccessDeniedHandler

            logout:
                path: app_logout
                success_handler: App\Security\LogoutSuccessHandler

            form_login:
                check_path: app_login
                login_path: app_login
                provider: app_provider

            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
                provider: app_provider

    access_control:
      - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }

      - { path: ^/post/(<\d+>)/comment, roles: [ROLE_ADMIN, ROLE_USER] }
      - { path: ^/post/(<\d+>)/comment/edit/(<\d+>), roles: [ROLE_ADMIN, ROLE_USER] }
      - { path: ^/survey/vote, roles: [ROLE_ADMIN, ROLE_USER] }

