version: "3"

services:
  database:
    image: postgres:10.6-alpine
    environment:
      - POSTGRES_DB=blog # same db name as production
      - POSTGRES_USER=blog # same user as production
      - POSTGRES_PASSWORD=asdf1234
    ports:
      - "127.0.0.1:5432:5432"
