version: "3"

services:
  database:
    image: postgres:11.1-alpine
    environment:
      - POSTGRES_DB=blogdb # same db name as production
      - POSTGRES_USER=postgres # same user as production
      - POSTGRES_PASSWORD=asdf1234
    ports:
      - "127.0.0.1:5432:5432"
